apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-container-idler
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-container-idler
  template:
    metadata:
      labels:
        app: faas-container-idler
    spec:
      containers:
      - name: faas-idler
        image: smarterlsy/faas-container-idler@sha256:93e07b68bcb3a4b0f42b9601f2f979e95e7e0411f84d471932600e4f426172fb
        imagePullPolicy: Always
        env:
          - name: inactivity_duration
            value: "5m"
        command:
          - /home/app/faas-idler