apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-timer
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-timer
  template:
    metadata:
      labels:
        app: vm-timer
    spec:
      containers:
      - name: vm-timer
        image: smarterlsy/vm-timer@sha256:dfb3c0e5eb74015597e26c6b46f1665c90c37f6c8f3525385aff07bcae16a921
        imagePullPolicy: Always
        env:
          - name: inactivity_duration
            value: "5m"
        command:
          - /home/app/vm-timer